# Generated by Django 5.2 on 2025-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='callback_time',
            field=models.CharField(choices=[('morning', 'Morning (9am - 12pm)'), ('afternoon', 'Afternoon (12pm - 5pm)'), ('evening', 'Evening (5pm - 8pm)'), ('anytime', 'Anytime')], default='anytime', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
