# Generated by Django 5.2 on 2025-05-07 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reviewinvitation_rename_quote_testimonial_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewinvitation',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='text',
            new_name='quote',
        ),
        migrations.RemoveField(
            model_name='reviewinvitation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='reviewinvitation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviewinvitation',
            name='used',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date',
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Optional, for personalizing the email.', max_length=200),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Has the invitation email been sent?'),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Has this invitation been used to submit a review?'),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve to display on site.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_submission', to='core.reviewinvitation'),
        ),
    ]
